# Generated by Django 5.1.2 on 2024-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('floor_number', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
                ('room_rent_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_rent_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_status', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('extra_capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
