# Generated by Django 5.1.2 on 2024-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bookings',
            field=models.ManyToManyField(blank=True, null=True, to='booking.booking'),
        ),
    ]
