# Generated by Django 5.1.2 on 2024-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_billing_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
