# Generated by Django 5.1.3 on 2024-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_billing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
